{{- if .Values.rbac.create -}}
apiVersion: {{ include "common.capabilities.rbac.apiVersion" . }}
kind: ClusterRole
metadata:
  name: {{ template "compose-operator.clusterRoleName" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - pods/exec
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - upm.syntropycloud.io
    resources:
      - mysqlgroupreplications
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - upm.syntropycloud.io
    resources:
      - mysqlgroupreplications/finalizers
    verbs:
      - update
  - apiGroups:
      - upm.syntropycloud.io
    resources:
      - mysqlgroupreplications/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - upm.syntropycloud.io
    resources:
      - mysqlreplications
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - upm.syntropycloud.io
    resources:
      - mysqlreplications/finalizers
    verbs:
      - update
  - apiGroups:
      - upm.syntropycloud.io
    resources:
      - mysqlreplications/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - upm.syntropycloud.io
    resources:
      - postgresreplications
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - upm.syntropycloud.io
    resources:
      - postgresreplications/finalizers
    verbs:
      - update
  - apiGroups:
      - upm.syntropycloud.io
    resources:
      - postgresreplications/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - upm.syntropycloud.io
    resources:
      - proxysqlsyncs
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - upm.syntropycloud.io
    resources:
      - proxysqlsyncs/finalizers
    verbs:
      - update
  - apiGroups:
      - upm.syntropycloud.io
    resources:
      - proxysqlsyncs/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - upm.syntropycloud.io
    resources:
      - redisclusters
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - upm.syntropycloud.io
    resources:
      - redisclusters/finalizers
    verbs:
      - update
  - apiGroups:
      - upm.syntropycloud.io
    resources:
      - redisclusters/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - upm.syntropycloud.io
    resources:
      - redisreplications
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - upm.syntropycloud.io
    resources:
      - redisreplications/finalizers
    verbs:
      - update
  - apiGroups:
      - upm.syntropycloud.io
    resources:
      - redisreplications/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - upm.syntropycloud.io
    resources:
      - units
    verbs:
      - get
      - list
      - patch
      - update
  - apiGroups:
      - upm.syntropycloud.io
    resources:
      - units/status
    verbs:
      - get
{{- end }}