# permissions for end users to edit redisreplications.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: redisreplication-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: compose-operator
    app.kubernetes.io/part-of: compose-operator
    app.kubernetes.io/managed-by: kustomize
  name: redisreplication-editor-role
rules:
- apiGroups:
  - upm.syntropycloud.io
  resources:
  - redisreplications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - upm.syntropycloud.io
  resources:
  - redisreplications/status
  verbs:
  - get
