name: Pull Request Checks

on:
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened]

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      go: ${{ steps.changes.outputs.go }}
      charts: ${{ steps.changes.outputs.charts }}
      docs: ${{ steps.changes.outputs.docs }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - uses: dorny/paths-filter@v3
      id: changes
      with:
        filters: |
          go:
            - '**/*.go'
            - 'go.mod'
            - 'go.sum'
            - 'Makefile'
          charts:
            - 'charts/**'
          docs:
            - 'docs/**'
            - '*.md'

  validate-pr:
    runs-on: ubuntu-latest
    steps:
    - name: Validate PR title
      uses: amannn/action-semantic-pull-request@v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        types: |
          feat
          fix
          docs
          chore
          refactor
          test
          ci
          deps
        requireScope: false

  test-go:
    uses: ./.github/workflows/test.yml
    needs: changes
    if: needs.changes.outputs.go == 'true'
    
  coverage-report:
    runs-on: ubuntu-latest
    needs: [changes, test-go]
    if: needs.changes.outputs.go == 'true' && github.event_name == 'pull_request'
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'

    - name: Generate coverage
      run: make test

    - name: Comment PR with coverage
      run: |
        COVERAGE=$(go tool cover -func=cover.out | tail -1 | awk '{print $3}')
        gh pr comment ${{ github.event.number }} --body "**Test Coverage**: $COVERAGE"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  validate-charts:
    runs-on: ubuntu-latest
    needs: changes
    if: needs.changes.outputs.charts == 'true'
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Helm
      uses: azure/setup-helm@v4
      with:
        version: v3.14.0

    - name: Add Helm repos
      run: |
        helm repo add bitnami https://charts.bitnami.com/bitnami

    - name: Lint Helm charts
      run: helm lint charts/compose-operator

    - name: Template Helm charts
      run: |
        helm template compose-operator charts/compose-operator \
          --values charts/compose-operator/values.yaml \
          --output-dir /tmp/helm-output

    - name: Validate templated manifests
      run: |
        curl -L https://github.com/yannh/kubeconform/releases/latest/download/kubeconform-linux-amd64.tar.gz | tar xz
        sudo mv kubeconform /usr/local/bin/
        find /tmp/helm-output -name "*.yaml" -exec kubeconform -summary -verbose {} \;
        
        
